---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: clang-format
  name: clang-format
  entry: cmake-pc-clang-format-hook
  description: Formats C/CPP code
  files: \.(c|cc|cu|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: clang-tidy
  name: clang-tidy
  entry: cmake-pc-clang-tidy-hook
  description: Find warnings/errors in C/CPP code
  files: \.(c|cc|cu|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: cppcheck
  name: cppcheck
  entry: cmake-pc-cppcheck-hook
  description: Find warnings/errors in C/CPP code
  files: \.(c|cc|cu|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: cpplint
  name: cpplint
  entry: cmake-pc-cpplint-hook
  description: Find warnings/errors in C/CPP code
  files: \.(c|cc|cpp|cu|cuh|cxx|h|hh|hpp|hxx)$
  language: python
- id: include-what-you-use
  name: include-what-you-use
  entry: cmake-pc-include-what-you-use-hook
  description: Find unused include directives in C/CPP code
  files: \.(c|cc|cu|cxx|cpp|h|hpp|hxx|m)$
  language: python
- id: lizard
  name: lizard
  entry: cmake-pc-lizard-hook
  description: Code complexity analyzer for C/CPP/ObjC/...
  files: \.(c|cc|cpp|cu|cuh|cxx|h|hh|hpp|hxx|py)$
  language: python
