[build-system]
requires = ["setuptools>=43", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

# ==============================================================================

[tool.black]
    line-length = 120
    target-version = ['py36','py37','py38']
    skip-string-normalization = true


[tool.check-manifest]
    ignore = [
    'PKG-INFO',
    '*.egg-info',
    '*.egg-info/*',
    'setup.cfg',
    '.hgtags',
    '.hgsigs',
    '.hgignore',
    '.gitignore',
    '.bzrignore',
    '.gitattributes',
    '.github/*',
    '.travis.yml',
    'Jenkinsfile',
    '*.mo',
    '.gitmodules',
    'VERSION.txt',
    '.editorconfig',
    '.envrc',
    '*.yml',
    '*.yaml',
    'MANIFEST.in',
    'docs/*',
    'docs/images/*',
    'misc/*',
    'tests/*',
    'tests/cmake_bad/*',
    'tests/cmake_good/*'
    ]


[tool.coverage]
    [tool.coverage.run]
        omit = [
            '*_test.py',
            '*_fixtures.py'
        ]


[tool.pylint]
    [tool.pylint.master]
    ignore-patterns = [
        '__init__.py'
    ]

    [tool.pylint.format]
    max-line-length = 120

    [tool.pylint.reports]
    msg-template = '{path}:{line}: [{msg_id}, {obj}] {msg} ({symbol})'

    [tool.pylint.messages_control]
    disable = [
         'invalid-name',
    ]


[tool.pytest.ini_options]
minversion = '6.0'
addopts = '-pno:warnings'
testpaths = ['cmake_pc_hooks']

[tool.isort]

profile = "black"

[tool.setuptools_scm]
write_to = 'VERSION.txt'
write_to_template = '{version}'
local_scheme = 'no-local-version'

[tool.yapf]
column_limit = 120
