---

name: "Draft new release"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version to release (format: vXX.YY.ZZ)'
        required: true

jobs:
  new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/setup.cfg'

      - name: Update CHANGELOG
        run: |
          python3 -m pip install mdformat-gfm 'git+https://github.com/Takishima/keepachangelog@v1.0.1'
          python3 -m keepachangelog release "${{ github.event.inputs.tag }}"
          python3 -m mdformat CHANGELOG.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        id: make-commit
        with:
          branch: release/${{ github.event.inputs.tag }}
          create_branch: true
          file_pattern: 'CHANGELOG.md'
          commit_message: Preparing release ${{ github.event.inputs.tag }}
          commit_author: github-actions[bot] <noreply@github.com>

      # yamllint disable rule:line-length
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.tag }}
          base: main
          title: Release version ${{ github.event.inputs.tag }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit_hash }}.
            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
