---

name: Pre-commit CHANGELOG autoupdate

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    name: "Pre-commit CI CHANGELOG auto-update"
    if: github.event.pull_request.title == '[pre-commit.ci] pre-commit autoupdate'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/setup.cfg'

      - name: Install dependencies
        run: |
          python3 -m pip install 'git+https://github.com/Takishima/pre-commit-changelog-auto-update@v1.0.0'

      - name: Run Python script
        run: |
          python3 -m update_changelog --pr-body "${{ github.event.pull_request.body }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG
          commit_author: github-actions[bot] <noreply@github.com>
